---
name: integration test
on: workflow_call
jobs:
  integration-test:
    permissions: {}
    timeout-minutes: 20
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on:
          - ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod
      - run: |
          go install -ldflags "-X main.version=v3.0.0-local -X main.commit=$GITHUB_SHA -X main.date=$(date +"%Y-%m-%dT%H:%M:%SZ%:z" | tr -d '+')" ./cmd/docfresh
      - run: docfresh -v
      # - run: docfresh init
      - run: docfresh run README.md examples/*.md
        env:
          DOCFRESH_GITHUB_TOKEN: ${{github.token}}
      - run: |
          if ! git diff --exit-code README.md examples; then
            echo "::error:: files are modified" >&2
            exit 1
          fi
